log_level: info

user_collector:
  update_interval: "10s"
  deactivate_after: "5m"
  cleanup_after: "7d"
  cleanup_interval: "1h"

db:
  driver: postgres
  database: ats_bot
  host: localhost
  port: 5432
  credentials:
    username: postgres
    password: 1234pass

server:
  recv_buf: 65536 # В байтах
  host: 127.0.0.1
  port: 8081