log_level: info

db:
  driver: postgres
  database: ats_bot
  host: localhost
  port: 5432
  credentials:
    username: postgres
    password: 1234pass

server:
  recv_buf: 65536 # В байтах
  host: 127.0.0.1
  port: 8080