log_level: info

user_collector:
  update_interval_secs: 10
  deactivate_after_minutes: 5
  cleanup_after_days: 7
  cleanup_interval_secs: 3600

db:
  driver: postgres
  database: ats_bot
  host: localhost
  port: 5432
  credentials:
    username: postgres
    password: 1234pass

server:
  recv_buf: 65536 # В байтах
  host: 127.0.0.1
  port: 8080